Unstructured-IO/base-images

dockerfiles/base-images:rocky8.7-1
bump tesseract version to `5.3.1`. This version is the latest stable release of tesseract and also the version in Ubuntu CI.
Built the docker image locally and checked version
```
tesseract 5.3.1
leptonica-1.75.1
libjpeg 6b (libjpeg-turbo 1.5.3) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 1.0.0
Found NEON
Found OpenMP 201511
```
=> bump tesseract version to sync with Ubuntu CI

dockerfiles/base-images:rocky9.2-9
When processing pdfs in Unstructured, certain hosts start returning `[digital envelope routines] unsupported`. To fix this, we need to enable legacy functions in openssl, similar to the discussion here: https://github.com/ethereum/execution-specs/issues/506
=> fix: enable legacy provider section in openssl

dockerfiles/base-images:rocky9.2-9
Revert https://github.com/Unstructured-IO/base-images/pull/12 which is too broad in scope. We've identified a more suitable fix.
=> revert: undo the legacy provider openssl fix

.github/workflows/ci.yml
Adds a missing double quote for the publish workflow matrix per the error [here](https://github.com/Unstructured-IO/base-images/actions/runs/7805198037/job/21294144570#step:5:2)
=> fix: add missing double quote for slim publish

Makefile, dockerfiles/deps/base.sh, dockerfiles/deps/python.sh, dockerfiles/deps/tesseract.sh
There is no pandoc install file with the `aarch64` arch designation and the following portion was never copied over during the last refactor: 
```shell
if [ "$ARCH" == "aarch64" ]; then
PANDOC_ARCH="arm64"
else
PANDOC_ARCH="amd64"
fi
```
This will now set the arch appropriately when pulling down the pandoc file.
=> bug: pandoc not being installed, fixed

.github/workflows/ci.yml
CI on main fails, because of removed login action to quay.io: https://github.com/Unstructured-IO/base-images/pull/19/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fL35-L40
It turns out that the `build-base-images.sh` script tries to push images, but only when on the `main` branch, that's why I didn't see any error:
=> fix: CI fails due to missing "Login to Quay.io" step

.github/workflows/ci.yml
Given that the ARM64 image isn't yet working, we're going to skip building it; therefore, skipping the attempt to publish a non-existent image makes sense too.
This PR attempt to fix such errors during the `publish-images` step on main
https://github.com/Unstructured-IO/base-images/actions/runs/9470215238/job/26097126232
=> fix: disable publishing of ARM64 wolfi-based image in CI

.github/workflows/ci.yml, dockerfiles/wolfi-base/Dockerfile
=> fix: syntax error in publish-images CI step and soffice initialization as non-root user

dockerfiles/wolfi-base/Dockerfile, scripts/docker-dl-wolfi-packages.sh
S3 location with APKs: https://utic-public-cf.s3.amazonaws.com
=> fix: install libreoffice 7 apk from s3

.github/workflows/ci.yml, .gitignore, dockerfiles/ubi9.4/Dockerfile, dockerfiles/wolfi-base/Dockerfile, melange/leptonica.yaml, melange/libreoffice.yaml, melange/openjpeg.yaml, melange/pandoc.yaml, melange/poppler.yaml, melange/tesseract.yaml, scripts/build-base-images.sh, scripts/docker-dl-wolfi-packages.sh, scripts/initialize-libreoffice.sh, scripts/install-wolfi-amd64-packages.sh
Updates the `wolfi-base` Dockerfile to support both `arm64` and `amd64` builds. Includes the following changes:
- Updates to the `melange` configs originally implemented by @tabossert on [this branch](https://github.com/Unstructured-IO/base-images/tree/trevor/melange) to build all of the packages except `libreoffice` for `arm64`.
- Scripts for different `arm64` and `amd64` install logic
- Enabling the `arm64` build in CI
Because we do not yet have an `arm64` build for `libreoffice`, the `arm64` version of the image does not currently support `.doc`, `.ppt`, or `.xls` documents, though it does support `.docx`, `.pptx`, and `.xlsx`.
There are following on issues to address the following items:
- Addresses a `pip` CVE that appeared on the scans in this PR, but is unrelated to the PR
- Follow …
=> build: enable arm64 build for wolfi-os

.github/workflows/ci.yml
Fix a bug in ci where the short hash was missing in the pull docker image step in the docker publish job.
=> fix: add short sha back to docker pull command

.github/workflows/ci.yml
Fixes a syntax error referencing the `SHORT_SHA` environment variable that appeared to cause [this CI job failure](https://github.com/Unstructured-IO/base-images/actions/runs/9686380207/job/26761297781).
=> fix: correct short sha env var syntax in publish

.github/workflows/ci.yml, dockerfiles/wolfi-base/Dockerfile, scripts/docker-dl-wolfi-packages.sh, scripts/initialize-libreoffice.sh, scripts/install-wolfi-libreoffice.sh
Per test failures on [this PR](https://github.com/Unstructured-IO/unstructured/pull/3310) in `unstructured`, the `libreoffice24` installation from the `wolfi-os` package manager does not convert `.ppt` files (though it does convert `.doc` files). This PR reverts to `libreoffice7` for the `amd64` image to avoid dropping support for `.ppt` in the `amd64` image. `libreoffice24` is still installed for the `arm64` image because that allows us to support one additional doc type (`.doc`) in the `arm64` `unsturcutred` image. We don't have a `libreoffice7` build currently for `arm64`.
Next steps on this are to try and debug why `libreoffice24` doesn't convert `.ppt`. Note that per [this PR](https://github.com/Unstructured-IO/base-images/pull/25), `libreoffice24` from the `wolfi` package manager …
=> fix: revert back to `libreoffice7` in `amd64` build

.github/workflows/ci.yml, dockerfiles/wolfi-base/Dockerfile, melange/libreoffice-24.yaml, scripts/docker-dl-wolfi-packages.sh, scripts/install-wolfi-libreoffice.sh
Bumps to `libreoffice-24.2.5.2` to address [CVE-2024-6472](https://www.libreoffice.org/about-us/security/advisories/CVE-2024-6472).
Image build should succeed with the update image. Additionally, @amadeusz-ds tested the updated APK with the API image.
=> build(CVE-2024-6472): bump to `libreoffice-24.2.5.2`

dockerfiles/wolfi-base/Dockerfile
This PR addresses the following issues:
- add `python-3.11-dev` and `glibc-dev` packages, which are necessary for installing the `lanms-neo` dependency required by `PaddleOCR`.
- add `git` package to enable installation of the latest version of `pytesseract` directly from the git source, as introduced in PR https://github.com/Unstructured-IO/unstructured/pull/3454/files#diff-c45ceb0e2d6f3f2b79349b98f8cf6002f8ac0aaf5e70afd8cf395eafc1c07f96R26.
=> add additional packages to wolfi-base

.github/workflows/ci.yml, dockerfiles/wolfi-base/Dockerfile
Adds Python 3.12 to `wolfi-base` to support bumping the `unstructured` and `unstructured-api` images to the 3.12. This PR also temporarily disables the rocky builds because failures in those jobs were blocking the wolfi builds.
=> build: add python 3.12 to wolfi-base

.github/workflows/ci.yml
Temporarily disables rocky linux in the publish step, since it's blocking publication of the `wolfi-base` image.
=> build: temporarily disable rocky

dockerfiles/wolfi-base/Dockerfile
Upstreams a temporary workaround to install `mesa-gl==24.1.0` because `libgallium` is missing from `mesa-gl==24.2.0` in the `wolfi` package manager. This was causing build errors in jobs like [this one](https://github.com/Unstructured-IO/core-product/actions/runs/10781356425/job/29899112925?pr=605).
```
> [model-deps 4/4] RUN --mount=type=secret,id=hf_token,uid=1000   export UNSTRUCTURED_HF_TOKEN=$(cat /run/secrets/hf_token) || true;   ./scripts/preload-models.sh:
9.719   File "/home/notebook-user/unstructured/unstructured/partition/utils/ocr_models/paddle_ocr.py", line 23, in __init__
9.719     self.agent = self.load_agent(language)
9.719                  ^^^^^^^^^^^^^^^^^^^^^^^^^
9.719   File "/home/notebook-user/unstructured/unstructured/partition/utils/ocr_models/paddle_ocr.py", line …
```
=> fix: install mesa-gl 24.1.0 due to libgallium missing

melange/libpst.yaml
Adds the melange config to build `libpst` for `wolfi-base`. The pipeline builds the CLI package, but not the Python bindings and the build pipeline does not include the man pages. Build has only been tested on `x86_64`.
To build the packages, run:
```
docker run --privleged --rm \
-v "${PWD}":/work \
cgr.dev/chainguard/melange \
build libpst.yaml \
--arch=x86_64 \
--signing-key melange.rsa
```
After the package is built, install it in `wolfi-base` with:
```
apk add --allow-untrusted libpst-0.6.76-r0.apk
```
Once it's installed, verify that `readpst` is available by runnign `readpst --help`.
=> build: add `melange` config for `libpst`

dockerfiles/wolfi-base/Dockerfile, melange/mesa.yaml, scripts/install-wolfi-mesa-gl.sh
In #44 , we implemented a workaround install `mesa-gl` 24.1 because `libgallium` was not included in `mesa-gl` 24.2 in the `wolfi` package manager, causing our builds to break. #44 only included an `amd64` `mesa-gl` package. This PR adds an `arm64` package, which will allow to fix downstream `arm64` builds that are currently broken.
=> fix: add `arm64` package for `mesa-gl`

scripts/docker-dl-wolfi-packages.sh, scripts/install-wolfi-mesa-gl.sh
Updates `wolfi` install scripts to detect the chip architecture and install the appropriate packages. Installing packages for the wrong architecture caused build errors in the `unstructured` repo.
[This job](https://github.com/Unstructured-IO/unstructured/actions/runs/10947571067/job/30396597670?pr=3647) successfully ran with the fix in the `unstructured` repo.
=> fix: detect arch in wolfi install scripts

.github/workflows/ci.yml, dockerfiles/deps/base.sh, dockerfiles/deps/python.sh
Fixes and reenables `rocky-linux` builds that have been broken for the past couple weeks. Implements the following updates:
- `python3-setuptools-53.0.0-12.el9.noarch` is no longer removed, because it doesn't get installed. It was previoulsy removed due to a CVE.
- Remove `dnf install cuda-driver`, because the CUDA drivers are provided by [`cuda-toolkit`](https://docs.nvidia.com/cuda/cuda-installation-guide-microsoft-windows/index.html#download-the-nvidia-cuda-toolkit) and [`nvidia-driver`](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/#driver-installation). The build was previously failing with `Error: Unable to find a match: cuda-driver`.
All images should now build on the feature branch.
=> fix: reenable `rocky-linux` build

dockerfiles/deps/python.sh
Upgrade python3.10 -> pytho3.12 for `deps/python.sh` script which applies to all base images except the wolfi images.
```
DOCKERFILE=rocky9.2-cpu  make build-base-images
docker run -it quay.io/unstructured-io/build-base-images:rocky9.2-cpu-amd64-c1fbebd /bin/bash
[root@f43a6a4b2a99 /]# python3 --version
Python 3.12.3
```
=> chore: upgrade python version to 3.12 for base images (except wolfi)

.github/workflows/chainguard.yml
=> Add chainguard image pull workflow

scripts/docker-dl-wolfi-packages.sh, scripts/install-wolfi-libreoffice.sh
Bump libreoffice to 25.2, which has a official package now on wolfi base repo. This PR also removes download of the outdated libreoffice 24 from script.
It also updates python 3.13 to 3.13.4-rc0 for a critical cve fix.
=> bump to official release of libreoffice 25.2

dockerfiles/wolfi-base/Dockerfile
update pytohn to 3.12 and resolve open CVEs in the base image
=> update the wolfi-base image to python 3.12
